services:
  authentication.api:
    image: authentication.api
    container_name: authentication.api
    build:
      context: .
      dockerfile: Authentication.API/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@authenticationDb:5432/AuthenticationDb"
    networks:
      - CryptoMarketNetwork
    depends_on:
      - authenticationDb
    ports:
      - "5002:5002"

  comments.api:
    image: comments.api
    container_name: comments.api
    build:
      context: .
      dockerfile: Comments.API/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@commentsDb:5432/CommentsDb"
    networks:
      - CryptoMarketNetwork
    depends_on:
      - commentsDb
    ports:
      - "5004:5004"

  orders.api:
    image: orders.api
    container_name: orders.api
    build:
      context: .
      dockerfile: Orders.API/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@ordersDb:5432/OrdersDb"
    networks:
      - CryptoMarketNetwork
    depends_on:
      - ordersDb
    ports:
      - "5005:5005"

  productsadministration.api:
    image: productsadministration.api
    container_name: productsadministration.api
    build:
      context: .
      dockerfile: ProductsAdministration.API/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@productsadministrationDb:5432/ProductsAdministrationDb"
    networks:
      - CryptoMarketNetwork
    depends_on:
      - productsadministrationDb
    ports:
      - "5001:5001"
        
  blockchain.api:
    image: blockchain.api
    container_name: blockchain.api
    build:
      context: .
      dockerfile: Blockchain.API/Dockerfile
    environment:
      BlockchainNodeUrl: "http://ganache:8545"
    depends_on:
      - ganache
      
    networks:
      - CryptoMarketNetwork
    ports:
      - "5006:5006"

  apigateway:
    image: apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - CryptoMarketNetwork
    ports:
      - "5000:5000"
  
  authenticationDb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "AuthenticationDb"
    networks:
      - CryptoMarketNetwork
    ports:
      - "5102:5432"
        
  commentsDb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "CommentsDb"
    networks:
      - CryptoMarketNetwork
    ports:
      - "5104:5432"
        
  ordersDb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "OrdersDb"
    networks:
      - CryptoMarketNetwork
    ports:
      - "5105:5432"
        
  productsadministrationDb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ProductsAdministrationDb"
    networks:
      - CryptoMarketNetwork
    ports:
      - "5101:5432"
        
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    networks:
      - CryptoMarketNetwork
    ports:
      - "5123:8545"
    
networks:
  CryptoMarketNetwork:
    driver: bridge
  
